#!/usr/bin/python3
# TODO mozno python3.8
import sys
import re
import socket
import ipaddress

def getArguments():
    if len(sys.argv) != 5:
        return False, None, None

    if not '-n' in sys.argv:
        return False
    else:
        index_n =  sys.argv.index('-n')  
        if index_n == 2 or index_n == 4:
            return False, None, None
        else:
            nameserver = sys.argv[index_n + 1]

    if not '-f' in sys.argv:
        return False, None, None
    else:
        index_f = sys.argv.index('-f')
        if index_f == 2 or index_f == 4:
            return False, None, None
        else:
            surl = sys.argv[index_f + 1]             

    return True, nameserver, surl


def processSurl(surl):
    # todo: fsp moze byt hocijako aj fSp
    if re.match(r"^(fsp|FSP)://([a-zA-Z]|[0-9]|[-_.])*/(.)*$", surl):
        temp = re.sub(r"^(fsp|FSP)://", '', surl)
        path = re.sub(r"^([a-zA-Z]|[0-9]|[-_.])*/", '', temp)
        server = re.sub(r"/(.)*$", '', temp)

        return True, server, path
    else:
        return False, None, None


def processNameserver(nameserver):
    if re.match(r"^([0-9]|[.])*:([0-9])*$", nameserver):
        ip = re.sub(r":([0-9])*$",'',nameserver)
        port = re.sub(r"^([0-9]|[.])*:", '', nameserver)
        port = int(port)

        try:
            ipaddress.ip_address(ip)
            #socket.inet_aton(ip) # TODO check
        # except socket.error:
        #     print('Invalid ip') # TODO vymazat
        #     return False
        except:
            return False, None, None

        if not 0 < port <= 65535:
            return False, None, None

        return True, ip, port
    else:
        return False, None, None   


if __name__ == "__main__":
    validArguments, nameserver, surl = getArguments()

    if not validArguments:
        print("error: invalid arguments", file=sys.stderr)
        sys.exit(-1)

    else:
        validSurl, server_surl, path_surl = processSurl(surl) 
        if not validSurl:
            print("error: invalid surl", file=sys.stderr)
            sys.exit(-1)

        validNameserver, ip_nameserver, port_nameserver = processNameserver(nameserver)
        if not validNameserver:
            print("error: invalid nameserver", file=sys.stderr)
            sys.exit(-1)

# -------------------------
# --- UDP communication
clientSocket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

sendstr = "WHEREIS " + server_surl
sendstr = bytes(sendstr, 'utf-8')

clientSocket.sendto(sendstr, (ip_nameserver, port_nameserver))
clientSocket.settimeout(5) # TODO raise exception if 5s is exceeded
received_data, address = clientSocket.recvfrom(1024) # buffer size is 1024bytes

print(received_data)
# print(address)

#clientSocket.connect()
#clientSocket.settimeout(30)

# UDP spojenie na nsp, posleme dotaz WHEREIS server, ten mi odpovie OK IP_adresa:port
# data sa vytvaraju po blokoch (datagramoch)
# ked chcem nieco poslat, musim datagram vytvorit, pomocou klientskeho soketu poslat na druhu stranu
# cakam na odpoved
# na konci zatvorim socket
# vytvorit socket -> send -> recv -> close


# serveru ip_nameserver a port_nameserver sa opytam where_is server_surl
# ten mi odpovie OK ipadresa:port

# potom tcp spojenim na novu ipadresu:port zavolam index a otvorim jeho obsah
# pozriem sa ci je v indexe dany subor
# stihanem dany subor, odstranim hlavicku
# vytvorim novy subor s rovnakym menom a ulozim do cwd

# ak je tam hviezdicka, musim stiahnut vsetky subory


# ./fileget -n 147.229.8.12:3333 -f fsp://foo.bar/file.txt
# stiahnem subor file.txt zo serveru foo.bar. Pre prklad mena serveru pouzijem nameserver 147.229.8.12
# pre stiahnutie suboru si najskor stiahnem foo.bar/index kt obsahuje vsetky subory, a tam sa pozriem ci dany subor existuje
# sprava pride vo viacerych segmentoch, teda dat while nejaky
# volat kym nepride cely subor
# pripojim sa na ip za -n, ziskam ip nameserveru, a z danej ip vezmem subor

# data zo suboru nemam citat, ale nechat ich v bajtoch file.write, file otvorti vo wb mode

# zapnutie serveru:
# hodim sa do os-x zlozky v ipk- servers a spustim:
# ./fsptest -p 127.0.0.1:3333 -r ../nameserver

# ---- INFO:
# WHEREIS server.one
# OK 127.0.0.1:58388

# WHEREIS server.two
# OK 127.0.0.1:58389

# symbolicke mena sa prekladaju na IP adresy pomocou protokolu NSP
# SURL: PROTOCOL://SERVER_NAME/PATH 
#       protocol - only TCP
#       server_name - moze byt tvorene len alfanumerickymi znakmi, -, _, a .

# ak subor najdem, ulozim ho do cwd
# ak nastane chyba, vhodnym sposobom ju vypiseme a ziadny subor nebude vytvoreny

# spustenie: fileget -n NAMESERVER -f SURL
# -n a -f mozu byt v hocakom poradi
    
# osetrit? ze * nemoze byt v podzlozke
# ci nameserver existuje poslem dotaz a dam timeout na odpoved
# .settimeout a exception na socket.timeout (5 sekund a niekto opakuje kazdy poziadavok 5x keby to bol docasny problem)
# port mozem otestovat aj tak ze dam try except pri connect
# index neukladat

# po kazdom get musim odpojit socket, connect a close dat do loopu kde volam get